config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  # get 'users/new'

  root to: 'static_pages#home'

  get 'signup'  => 'users#new'
  get 'show'    => 'users#show'
  post 'users/edit/:id'   => 'users#edit', as: :edit_user
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout'=> 'sessions#destroy'
  get 'topics'  => 'topics#show', as: :topics
  get 'posts/:id'   => 'posts#show', as: :posts
  delete 'posts/:id'  => 'posts#destroy', as: :destroy_post
  delete 'topics/:id' => 'topics#destroy', as: :destroy_topic
  get 'create_posts/:id'    => 'posts#new', as: :create_post
  post 'posts/:id'    => 'posts#create', as: :add_post
  get 'create_topic'  => 'topics#new', as: :create_topic
  post 'topics'   => 'topics#create'


  resources :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :posts

  validates :title, presence: true, length: {minimum: 5, maximum: 50}
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  before_save { self.email.downcase! }

  validates :name, presence: true, length: {minimum: 3, maximum: 50}
  validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, length: {minimum: 6}, presence: true

  has_secure_password

  has_and_belongs_to_many :topics
  has_many :posts

  Roles = [:admin, :default]

  def is?(requested_role)
    self.role == requested_role
  end


  def admin?()
    self.admin
  end

  def created_post?(post)
    self == post.user
  end

  def created_topic?(topic)
    self == topic.user
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new

    @post = Post.new
  end

  def create
    @post = @post = Post.new(post_params)
    topic_id = params[:id]
    topic = Topic.find(topic_id)
    topic.users << current_user unless topic.users.include?(current_user)

    @post.user = current_user
    @post.topic = topic

    @post.save


    redirect_to posts_path(topic_id)
  end

  def show
    id = params[:id]

    # @posts = Post.find_by(topic_id: id)
    @posts = Post.where("topic_id = #{id}").order("created_at DESC")
  end

  def destroy
    id = params[:id]

    post = Post.find(id)
    topic_id = post.topic.id

    post.destroy

    redirect_to posts_path(topic_id)
  end

  private

  def post_params
    params.require(:post).permit(:text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      flash[:success] = "Sikeres bejelentkezés"
      redirect_to :topics
    else
      flash.now[:danger] = "Érvénytelen email/jelszó kombináció"
      render 'new'
    end
  end

  def destroy
    logout if logged_in?
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      redirect_to :topics
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def show
    @topics = Topic.all
  end

  def new
    @topic = Topic.new
  end

  def create
    # @topic = Topic.new(params.require(:topic).permit(:title))
    @topic = Topic.new
    @topic.title = params.require(:topic).permit(:title)[:title]

    if @topic.save
      @topic.users << current_user
      flash[:success] = "Fórumtéma létrehozva"
      redirect_to topics_path
    else
      flash[:danger] = "Fórumtéma létrehozása sikertelen"
      redirect_to topics_path
    end
  end

  def destroy
    id = params[:id]

    topic = Topic.find(id)

    topic.destroy

    redirect_to topics_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])

    @user.name = user_params[:name]
    @user.password = user_params[:password]

    if @user.save
      flash[:success] = "Adatok módosítva"
      redirect_to root_path
    else
      render 'show'
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Sikeres regisztráció"
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def author(post)
    user_id = post.user_id

    @user = User.find(user_id)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Forum on rails", root_path, id: "logo" %>

    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Kezdőoldal", root_path %></li>

        <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Profil <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profil beállítások", @current_user %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Kijelentkezés", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Bejelentkezés", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class ="container">
  <% flash.each do |message_type, message| %>
      <div class="<%= "alert alert-#{message_type}" %>"> <%= message %> </div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/posts/new.html.erb
<h2> Hozzászólok: </h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@post) do |f| %>
        <%= f.label :text, "Hosszászólás tartalma:" %>
        <%= f.text_area :text, class: 'form-control' %>

        <%= f.submit "Hozzászólás elküldése", class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div>

  <%= link_to "Hozzászólás írása", create_post_path(params[:id]) %>

  <% @posts.each do |p| %>
      <div class="post">
        <div class="post-profile">
          <span class="post-username"><%= link_to p.user.name, p.user %><br /></span>
          <span class="post-numberofposts"><%= "Hozzászólások száma: #{p.user.posts.count}" %><br /></span>
          <span class="post-joined"><%= "Csatlakozott: #{p.user.created_at.to_date}" %></span>
        </div>

        <div class="post-date">
          <%= p.created_at %>
        </div>

        <% if current_user.admin? || current_user.created_post?(p) %>
            <span class="post-delete"><%= link_to "törlés", destroy_post_path(p.id), method: :delete %></span>
        <% end %>

        <div class="post-content">
          <%= p.text %>
        </div>
      </div>
  <% end %>
</div>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Üdvözöllek a fórumon</h1>

  <h2>
    Ez a kezdőoldala a fórum on rails alkalmazásnak, amely a Ruby on Rails egyetemi kurzus alatt készült.
  </h2>

  <%= link_to "Regisztráció", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<!--<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %>-->

app/views/topics/new.html.erb
<h2> Topic létrehozása: </h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@topic) do |f| %>
        <%= f.label :title, "Fórum téma címe:" %>
        <%= f.text_field :title, class: 'form-control' %>

        <%= f.submit "Fórum téma létrehozása", class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<div>
  <%= link_to "Fórumtéma létrehozása", create_topic_path if current_user.admin? %>
  <% @topics.each do |t| %>
      <%= link_to posts_path(t.id) do %>
          <div class="row topic-row">

            <span class="topic-title">
              <%= t.title %>
            </span>

            <span class="topic-creation-date">
              at: <%= t.created_at %>
            </span>

            <span class="topic-owner">
              Created by: <%= t.users[0].name %>
            </span>

            <% if current_user.admin? %>
                <span>
                <%= link_to "Törlés", destroy_topic_path(t.id), class: 'topic-delete', method: :delete %>
                </span>
          <% end %>
          </div>
      <% end %>
  <% end %>
</div>

app/views/users/_edit_user.html.erb
<h2> Adatok módosítása: </h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:user, url: edit_user_path) do |f| %>
        <%= f.label :name, "Név módosítása" %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :password, "Jelszó módosítása" %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Jelszó mégegyszer" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Adatok mentése", class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Regisztráció</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name, "Név" %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email, "E-mail cím" %>
        <%= f.email_field :email, class: 'form-control'  %>

        <%= f.label :password, "Jelszó" %>
        <%= f.password_field :password, class: 'form-control'  %>

        <%= f.label :password_confirmation, "Jelszó mégegyszer" %>
        <%= f.password_field :password_confirmation, class: 'form-control'  %>

        <%= f.submit "Felhasználó létrehozása", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>

      <div>Regisztráció dátuma: <%= @user.created_at %></div>
      <div>Létrehozott topicok száma: <%= @user.topics.count %></div>
      <div>Posztok száma: <%= @user.posts.count %> </div>
      <!--<div>Utolsó bejelentkezés: <%= Time.now %></div>-->
    </section>

    <a href="#" onclick="show_user_editor('.user-editor')">Profil szerkesztése</a>

    <div class="user-editor">
      <%= render 'edit_user' %>
    </div>
  </aside>
</div>